# Generated by Django 6.0.8 on 2026-08-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_greenzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenzone',
            name='location_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='greenzone',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greenzone',
            name='reminder_frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly')], default='Weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='greenzone',
            name='timer_status',
            field=models.CharField(default='Scheduled', max_length=50),
        ),
    ]
