# Generated by Django 6.0.8 on 2026-08-13 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_greenzone_location_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.CharField(default='COMP-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(default='Up to date', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='zone',
            field=models.CharField(default='Zone North', max_length=100),
        ),
        migrations.AddField(
            model_name='greenzone',
            name='area_size',
            field=models.CharField(default='100 m²', max_length=50),
        ),
        migrations.AddField(
            model_name='greenzone',
            name='current_metric',
            field=models.CharField(default='85% Humidity', max_length=50),
        ),
        migrations.AddField(
            model_name='greenzone',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='api.company')),
            ],
        ),
    ]
