# Generated by Django 6.0.8 on 2026-08-13 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_company_code_company_status_company_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='operated_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Facility Manager'), ('operator', 'Operador en campo')], default='manager', max_length=20),
        ),
    ]
