# Generated by Django 6.0.8 on 2026-08-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_company_operators_company_user_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenzone',
            name='polygon_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
