# Generated by Django 6.0.8 on 2026-08-14 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_greenzone_polygon_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_this_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='api.company'),
        ),
    ]
